// <auto-generated />
using Bimbelku.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bimbelku.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220409223554_soal")]
    partial class soal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Bimbelku.Models.Materi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("FileMateri")
                        .HasColumnType("text");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text");

                    b.Property<string>("Mapel")
                        .HasColumnType("text");

                    b.Property<string>("NamaMateri")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Materi");
                });

            modelBuilder.Entity("Bimbelku.Models.Roles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Roles");
                });

            modelBuilder.Entity("Bimbelku.Models.Soal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FileSoal")
                        .HasColumnType("text");

                    b.Property<string>("Mapel")
                        .HasColumnType("text");

                    b.Property<string>("Waktu")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Soal");
                });

            modelBuilder.Entity("Bimbelku.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("RolesId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Username");

                    b.HasIndex("RolesId");

                    b.ToTable("Tb_User");
                });

            modelBuilder.Entity("Bimbelku.Models.User", b =>
                {
                    b.HasOne("Bimbelku.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
